### ISSUE TITLE
Modelling Relationships with Type Information and Description

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#10]
### Description of Problem:

I want to model relationships with concrete types, this will make it easier when processing and interpreting the model. I would like to propose we start with the following types of relationship:

- `connects`
- `contains`
- `deployed-in`

Prior to adding this it would be good to hear from others additional items for inclusion.

I would also propose that we add support for an optional `description`

### Potential Solutions:

This is currently a string, modelling as a type within an enum will avoid naming issues and make the model more parsable/usable when reviewing architectures programatically

**Comment by Budlee** [comment]
Hey,
I have started working with the CALM model to take the Trader-X example and transform it to C4 and am having this exact issue.

In the Trader-X example I notice four relationship types as strings:

* `connect` - for nodes that connect together
* `composed-of` - the nodes, which are all of type service, are in a system
* `deployed-in` - the nodes, which are all of type service, are in a network 
* `interacts` - Actor to nodes

In order to model any sort of hierarchy and structure I agree with Jim that we would want to have defined types of connections.

My thought is that we slightly change the defined types. 

## Suggestion 1
What we see in the current model is that `composed-of` and `deployed-in` are equivalent in the example structure:

```json
 {
    "uniqueId": "traderx-system-is-deployed-in-internal-bank-network",
    "type": "deployed-in",
    "parties": {
      "nodes": [
        "traderx-system"
      ],
      "container": "internal-bank-network"
    }
  },
  {
    "uniqueId": "traderx-system-is-composed-of",
    "type": "composed-of",
    "parties": {
      "nodes": [
        "web-client",
        "web-gui-process",
        "position-service",
        "traderx-db"
      ],
      "container": "traderx-system"
    }
```

Could composed-of and deployed-in be merged under a single name. Both are stating what nodes exist in what container?

## Suggestion 2

 `connects` and  `interacts` both have different structures, however, could these be merged? `connects` defines a relationship between two nodes, while interact is defining a connection  between an actor and multiple nodes. Could/should we look at `connects` to multiple nodes or `interacts` being to a singular node like `connects`?

```
  "uniqueId": "trader-uses-web-client",
      "type": "interacts",
      "parties": {
        "actor": "traderx-trader",
        "nodes": [
          "web-client"
        ]
      }
    },
    {
      "uniqueId": "web-client-uses-web-gui",
      "type": "connects",
      "parties": {
        "source": "web-client",
        "destination": "web-gui-process"
      },
      "protocol": "HTTPS",
      "authentication": "SiteMinder/Isolated"
    },
```

## Summary 

I would like to define the relationship type as Jim has suggested, however, instead of it being just an enum  I'd like to take it further and have a structured type of the relationship type.

**Comment by jpgough-ms** [comment]
@Budlee I like the idea of

> instead of it being just an enum I'd like to take it further and have a structured type of the relationship type.

I wonder though whether the structured type of relationship would be too opinionated to a given organisation. Perhaps we should make the enum change and then revisit your suggestion in a new issue?

**Comment by jpgough-ms** [comment]
@Budlee #15 does this resolve your commentary on this original issue?

**Comment by Budlee** [comment]
The enum helps, however, I do still like the idea of stronger definitions around relationship types and I don't think we need all four values. As I mentioned above we see equivalence in composed-of and deployed-in and connects and interacts are pretty much the same.

**Comment by jpgough-ms** [comment]
@Budlee do you want a PR with what you are trying to get to with stronger definitions?

**Comment by rocketstack-matt** [comment]
I'd disagree that they're the same thing . . .
* composed-of provides a logical architecture view where as deployed-in provides a physical view
* connects is intended for service to service where as interacts is for a user to service

I think what we should actually be doing is providing conditional logic around the relationships to restrict where they can be uses so they've not misused.

**Comment by Budlee** [comment]
I’ll make a small PR with suggestions on it. Is there a development tool you recommend for generating the schema?

**Comment by rocketstack-matt** [comment]
IntelliJ seems to provide the best json schema support.

**Comment by Budlee** [comment]
@jpgough-ms happy to close this question?
